### ISSUE TITLE
Root directory does not exist

### ISSUE THREAD

**Issue by donwany** [bayesgroup/deep-weight-prior#1]
Traceback (most recent call last):
  File "train-vae.py", line 116, in <module>
    parser = myexman.ExParser(file=__file__)
  File "/Users/tsiameh/Desktop/PhD. MSU/Fall 2020/Topics in Ai/Project/keras-covid19-detection/deep-weight-prior/myexman/parser.py", line 145, in __init__
    **kwargs)
  File "/Users/tsiameh/Desktop/PhD. MSU/Fall 2020/Topics in Ai/Project/keras-covid19-detection/deep-weight-prior/myexman/parser.py", line 71, in __init__
    raise ValueError(root, 'Root directory does not exist')
ValueError: (PosixPath('/Users/tsiameh/Desktop/PhD. MSU/Fall 2020/Topics in Ai/Project/keras-covid19-detection/deep-weight-prior/exman-train-vae.py'), 'Root directory does not exist')
![Screen Shot 2020-10-25 at 4 18 20 PM](https://user-images.githubusercontent.com/10055091/97119366-bc706c80-16dd-11eb-8dde-2d742841d23d.png)

**Comment by donwany** [comment]
How do I set the root directory on mac book.

export DATA_ROOT=<path to MNIST/notMNIST>
export DWP_PATH=<path to logs to save>

**Comment by AndrewAtanov** [comment]
Hello! 
Set DATA_ROOT to the directory where do you want to store the MNIST/notMNIST dataset (it will be loaded automatically). 
Set DWP_PATH to the directory where you want to store your logs. You can find logs then at <DWP_PATH>/exman-<training script>/runs/<id>. With the last commit, the directory will be created automatically.

**Comment by AndrewAtanov** [comment]
Hello!
Set DATA_ROOT to the directory where do you want to store the MNIST/notMNIST dataset (it will be loaded automatically).
Set DWP_PATH to the directory where you want to store your logs. You can find logs then at <DWP_PATH>/exman-/runs/. With the last commit, the directory will be created automatically.

**Comment by donwany** [comment]
Thanks I will try that again

**Comment by donwany** [comment]
![Screen Shot 2020-10-27 at 1 53 37 PM](https://user-images.githubusercontent.com/10055091/97348321-f8c9d700-185b-11eb-9e48-c90d1d0bbb8e.png)
![Screen Shot 2020-10-27 at 1 54 28 PM](https://user-images.githubusercontent.com/10055091/97348334-fcf5f480-185b-11eb-8f7f-ed6623f006fa.png)

environment variables DATA_ROOT and DWP_PATH set but error still says <Root directory does not exist>

**Comment by senya-ashukha** [comment]
I think it is safe to create the directory by `mkdir <dir>` :)

**Comment by donwany** [comment]
@senya-ashukha  I actually used mkdir -p /Users/tsiameh/Desktop/PhD.MSU/Fall2020/TopicsInAi/Project/keras-covid19-detection/deep-weight-prior/logs

**Comment by AndrewAtanov** [comment]
But you need to create `/Users/tsiameh/Desktop/PhD.MSU/Fall2020/TopicsInAi/Project/keras-covid19-detection/deep-weight-prior/logs/exman-train-net.py`

Did you pull the last commit? It should create the directory automatically.

**Comment by donwany** [comment]
![Screen Shot 2020-10-27 at 6 10 25 PM](https://user-images.githubusercontent.com/10055091/97371671-c92cc600-187f-11eb-8177-441ae83a7280.png)

That is the latest error after pulling the new repository.

**Comment by donwany** [comment]
It works now. Thanks for the help.
